# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode11
language: swift

xcode_project: Reggie.xcodeproj
xcode_scheme: Reggie macOS
xcode_destination: platform=macOS

script:
- set -o pipefail
  && xcodebuild test
      -project Reggie.xcodeproj
      -scheme 'Reggie macOS'
      -sdk macosx10.15
  | xcpretty
- swift test
