# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: beta-xcode8.3
language: objective-c

xcode-project: Reggie.xcodeproj
xcode_scheme: Reggie

script:
- set -o pipefail && xcodebuild clean build test -project Reggie.xcodeproj -scheme Reggie | xcpretty
- pod lib lint
