# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: beta-xcode8.4
language: objective-c

before_install:
- gem install cocoapods # Since Travis is not always on latest version

script:
- set -o pipefail
  && xcodebuild clean build test
      -project Reggie.xcodeproj
      -scheme 'Reggie iOS Tests'
      -sdk iphonesimulator8.0
      -destination 'platform=iOS Simulator,OS=8.0,name=iPhone 5'
  | xcpretty
- set -o pipefail
  && xcodebuild
      test
      -project Reggie.xcodeproj
      -scheme 'Reggie macOS Tests'
      -sdk macosx10.10
      -destination 'platform=OS X'
  | xcpretty
- pod lib lint
